/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class harga_dobi extends javax.swing.JFrame {

    /**
     * Creates new form harga_dobi
     */
    public harga_dobi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        hargaTF = new javax.swing.JTextField();
        hargaLabel = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        hariCombo = new javax.swing.JComboBox<>();
        beratTF = new javax.swing.JTextField();
        beratLabel = new javax.swing.JLabel();
        hariLabel = new javax.swing.JLabel();
        silamasukkanmaklumat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        namaaplikasi = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        beratLabel1 = new javax.swing.JLabel();
        basuhCB = new javax.swing.JCheckBox();
        keringCB = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(177, 156, 216));

        hargaTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        hargaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargaLabel.setForeground(new java.awt.Color(227, 227, 252));
        hargaLabel.setText("Harga (RM):");

        enterButton.setBackground(new java.awt.Color(204, 204, 255));
        enterButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterButton.setText("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        hariCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hariCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "Isnin", "Selasa", "Rabu", "Khamis", "Jumaat", "Sabtu", "Ahad" }));

        beratTF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        beratLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        beratLabel.setForeground(new java.awt.Color(227, 227, 252));
        beratLabel.setText("Berat Pakaian (KG):");

        hariLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hariLabel.setForeground(new java.awt.Color(227, 227, 252));
        hariLabel.setText("Hari Penggunaan Dobi:");

        silamasukkanmaklumat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        silamasukkanmaklumat.setForeground(new java.awt.Color(227, 227, 252));
        silamasukkanmaklumat.setText("Sila Masukkan Maklumat Berikut:");

        table1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        table1.setForeground(new java.awt.Color(155, 115, 179));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mesin Basuh", "5 per KG"},
                {"Mesin Kering", "7 per KG"}
            },
            new String [] {
                "Jenis Mesin", "Kadar Harga (RM)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setResizable(false);
            table1.getColumnModel().getColumn(1).setResizable(false);
        }

        table2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        table2.setForeground(new java.awt.Color(155, 115, 179));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Isnin hingga Jumaat", "7%"},
                {"Sabtu dan Ahad", "tiada"}
            },
            new String [] {
                "Hari", "Diskaun"
            }
        ));
        jScrollPane2.setViewportView(table2);

        namaaplikasi.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        namaaplikasi.setForeground(new java.awt.Color(227, 227, 252));
        namaaplikasi.setText("Aplikasi Kiraan Bayaran Dobi");

        clearButton.setBackground(new java.awt.Color(204, 204, 255));
        clearButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(204, 204, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        beratLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        beratLabel1.setForeground(new java.awt.Color(227, 227, 252));
        beratLabel1.setText("Jenis Mesin:");

        basuhCB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        basuhCB.setForeground(new java.awt.Color(227, 227, 252));
        basuhCB.setText("Mesin Basuh");
        basuhCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basuhCBActionPerformed(evt);
            }
        });

        keringCB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        keringCB.setForeground(new java.awt.Color(227, 227, 252));
        keringCB.setText("Mesin Kering");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaaplikasi)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(silamasukkanmaklumat)
                        .addGap(61, 61, 61)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaLabel))))
                .addGap(131, 131, 131))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(hariLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hariCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGap(229, 229, 229)
                                    .addComponent(beratTF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(beratLabel1)
                                        .addComponent(beratLabel))
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(keringCB))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(basuhCB, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(namaaplikasi)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(silamasukkanmaklumat)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beratLabel)
                            .addComponent(beratTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(beratLabel1)
                            .addComponent(basuhCB)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(hargaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keringCB)
                        .addGap(20, 20, 20)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hariCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hariLabel))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterButton)
                    .addComponent(exitButton))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        //EXIT
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //CLEAR
        beratTF.setText("");
        hargaTF.setText("");
        hariCombo.setSelectedIndex(0);
        basuhCB.setSelected(false);
        keringCB.setSelected(false);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        //ENTER
        int berat;
        String hari;
        double harga=0;
        hari=hariCombo.getSelectedItem().toString();

        berat=Integer.parseInt(beratTF.getText());

        if(basuhCB.isSelected()&&keringCB.isSelected()){
            harga=(berat*5)+(berat*7);
        }else if(basuhCB.isSelected()){
            harga=berat*5;
        }else if(keringCB.isSelected()){
            harga=berat*7;
        }

        if("Isnin".equals(hari)||"Selasa".equals(hari)||"Rabu".equals(hari)||"Khamis".equals(hari)||"Jumaat".equals(hari)){
            double hargaakhir=harga*93/100;
            hargaTF.setText(Double.toString(hargaakhir));
        }else if("Sabtu".equals(hari)||"Ahad".equals(hari)){
            hargaTF.setText(Double.toString(harga));
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void basuhCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basuhCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basuhCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(harga_dobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(harga_dobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(harga_dobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(harga_dobi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new harga_dobi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox basuhCB;
    private javax.swing.JLabel beratLabel;
    private javax.swing.JLabel beratLabel1;
    private javax.swing.JTextField beratTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JTextField hargaTF;
    private javax.swing.JComboBox<String> hariCombo;
    private javax.swing.JLabel hariLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox keringCB;
    private javax.swing.JLabel namaaplikasi;
    private java.awt.Panel panel1;
    private javax.swing.JLabel silamasukkanmaklumat;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
