/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form utama
     */
    public utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tiketwayang = new javax.swing.JButton();
        sewakereta = new javax.swing.JButton();
        kiraanbayarandobi = new javax.swing.JButton();
        vendingmachine = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(138, 139, 180));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROJEK APLIKASI APAI");

        tiketwayang.setBackground(new java.awt.Color(188, 196, 219));
        tiketwayang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tiketwayang.setText("Sistem Tiket Wayang");
        tiketwayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiketwayangActionPerformed(evt);
            }
        });

        sewakereta.setBackground(new java.awt.Color(192, 169, 176));
        sewakereta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sewakereta.setText("Sistem Tiket Parking Kereta");
        sewakereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewakeretaActionPerformed(evt);
            }
        });

        kiraanbayarandobi.setBackground(new java.awt.Color(156, 149, 179));
        kiraanbayarandobi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kiraanbayarandobi.setText("Sistem Kiraan Bayaran Dobi");
        kiraanbayarandobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiraanbayarandobiActionPerformed(evt);
            }
        });

        vendingmachine.setBackground(new java.awt.Color(138, 139, 180));
        vendingmachine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        vendingmachine.setText("Sistem Vending Machine");
        vendingmachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendingmachineActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(208, 226, 243));
        jLabel2.setText("Sila memilih sistem anda:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(sewakereta, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tiketwayang, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kiraanbayarandobi, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vendingmachine, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(82, 82, 82)))
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(tiketwayang)
                .addGap(43, 43, 43)
                .addComponent(sewakereta)
                .addGap(44, 44, 44)
                .addComponent(kiraanbayarandobi)
                .addGap(46, 46, 46)
                .addComponent(vendingmachine)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sewakeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewakeretaActionPerformed
        // TODO add your handling code here:
        SistemParking jf2 = new SistemParking();
        jf2.show();
        dispose();
    }//GEN-LAST:event_sewakeretaActionPerformed

    private void kiraanbayarandobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiraanbayarandobiActionPerformed
        // TODO add your handling code here:
        harga_dobi jf3 = new harga_dobi();
        jf3.show();
        dispose();
    }//GEN-LAST:event_kiraanbayarandobiActionPerformed

    private void vendingmachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendingmachineActionPerformed
        // TODO add your handling code here:
        VendingMachine jf4 = new VendingMachine();
        jf4.show();
        dispose();
    }//GEN-LAST:event_vendingmachineActionPerformed

    private void tiketwayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiketwayangActionPerformed
        // TODO add your handling code here:
        AplikasiTiketWayang jf1 = new AplikasiTiketWayang();
        jf1.show();
        dispose();
    }//GEN-LAST:event_tiketwayangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kiraanbayarandobi;
    private javax.swing.JButton sewakereta;
    private javax.swing.JButton tiketwayang;
    private javax.swing.JButton vendingmachine;
    // End of variables declaration//GEN-END:variables
}
